# Generated by Django 4.2.13 on 2024-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(max_length=15, verbose_name='Fa Icon')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image', models.ImageField(upload_to='media/services', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Short Description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
