# Generated by Django 4.2.13 on 2024-05-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='PostTags',
            new_name='PostTag',
        ),
    ]
